services:
  - type: web
    name: coursehub-web
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python scripts/init_db.py && python scripts/seed.py && gunicorn --bind 0.0.0.0:$PORT run:app
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: coursehub-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        value: 8740701480:AAHV9akw5_rj0wxs8jVHRXVGo18Sa3XEJEM
      - key: PUBLIC_BASE_URL
        value: https://courcehub.onrender.com
      - key: TELEGRAM_WEB_APP_URL
        value: https://courcehub.onrender.com/telegram/

  - type: worker
    name: coursehub-bot
    runtime: python
    plan: starter
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python -m bot.main
    envVars:
      - key: SECRET_KEY
        fromService:
          name: coursehub-web
          type: web
          envVarKey: SECRET_KEY
      - key: DATABASE_URL
        fromDatabase:
          name: coursehub-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        value: 8740701480:AAHV9akw5_rj0wxs8jVHRXVGo18Sa3XEJEM
      - key: PUBLIC_BASE_URL
        value: https://courcehub.onrender.com
      - key: TELEGRAM_WEB_APP_URL
        value: https://courcehub.onrender.com/telegram/

databases:
  - name: coursehub-db
    region: frankfurt
    databaseName: coursehub
    user: coursehub
